# Site settings
title: Nifqi Blog
header-img: img/home-bg.jpg
email: mail@nifqi.com
copyright_name: Your/Project/Corporate Name
description: "Blog percobaan"
baseurl: "/anu"
url: "http://nifqi.github.io"
twitter_username: nifqi
github_username:  nifqi
facebook_username:  nifqi
email_username:  mail@nifqi.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
